name: run unit tests
on: 
  push:
    branches:
      - master
      - dev
      - upload-artifact
jobs:
#   unit_test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Install modules
#       run: npm ci
#     - name: Run tests
#       run: npm run test:unit

  artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm ci --production
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist-files
          path: dist/
